### ISSUE TITLE
Indent line is slanted on italic font.

### ISSUE THREAD

**Issue by hiddenruins** [lukas-reineke/indent-blankline.nvim#72]
Just tried this plugin, which is awesome btw, and I get slanted indent lines when the font is italic.

- Branch: lua
- Font: Monolisa
- Theme: [Gruvbox Material](https://github.com/sainnhe/gruvbox-material)

Settings
```lua
vim.g.indent_blankline_char= '┊'
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
```

![slanted-indent](https://user-images.githubusercontent.com/5569621/112453202-8c59f200-8d7f-11eb-8d4c-f0a99fcf84b4.png)

![image](https://user-images.githubusercontent.com/5569621/112454624-fcb54300-8d80-11eb-9d03-596c9055b644.png)

**Comment by lukas-reineke** [comment]
Thank you. I pushed a fix for this now.

The problem was the virtual text with `hl_mode = "combine"` also takes over the highlight gui options from the underlying text.

The fix has to be a breaking change.. I had to remove the highlight options. Instead, you have to update or define highlight groups now.

The new groups are `IndentBlanklineChar` `IndentBlanklineSpaceChar` and `IndentBlanklineSpaceCharBlankline`

**Comment by hiddenruins** [comment]
Thank you. It's working properly now. :)

**Comment by space-blaster** [comment]
still have this issue with:
- latest indent-blankline.nvim
- latest folke/tokyonight.nvim

![image](https://user-images.githubusercontent.com/83952896/195488693-8197d60c-88a4-4066-a269-927bdcab57c8.png)

**Comment by lukas-reineke** [comment]
This is an issue with tokyonight. I made a PR to fix it https://github.com/folke/tokyonight.nvim/pull/247

**Comment by likunyao** [comment]
still have this issue with sainnhe/gruvbox-material
```
vim.api.nvim_set_var('indent_blankline_char', '¦')
vim.api.nvim_set_var('indent_blankline_show_first_indent_level', false)

indent_blankline.setup({
     -- for example, context is off by default, use this to turn it on
    show_current_context = true,
    show_current_context_start = false,
})
```
![1668055320360](https://user-images.githubusercontent.com/16969814/201002395-6e55e78d-d295-4a0e-ae31-a3635b7a318f.jpg)

**Comment by lukas-reineke** [comment]
Then open an issue in sainnhe/gruvbox-material
this is a problem with the color scheme
