### ISSUE TITLE
Indentlines are not dimmed

### ISSUE THREAD

**Issue by Gelio** [lukas-reineke/indent-blankline.nvim#73]
Hey, thanks for this great extension 👍 

After today's update I have noticed that the indentlines are quite bright:

![image](https://user-images.githubusercontent.com/889383/112520692-f8e2ea00-8d9b-11eb-8a70-497d866cc328.png)
![image](https://user-images.githubusercontent.com/889383/112520712-fda79e00-8d9b-11eb-95fa-e6422ede1ed5.png)

Theme: gruvbox

After reverting 80263915421bb27c800e07fea5b3a70674ca3c01 and 6b5e3edd05753746b9eae45079607ff126ea349e, it's back to normal:

![image](https://user-images.githubusercontent.com/889383/112521066-5f680800-8d9c-11eb-8be4-8e34abdc0402.png)

I have not modified anything in my config otherwise.

Part of `init.vim` related to this extension:

```vim
	Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }
	let g:indent_blankline_show_current_context = v:true
	let g:indent_blankline_context_patterns = ['class', 'function', 'method',
				\ 'if_statement', 'else_clause', 'jsx_element', 'jsx_self_closing_element',
				\ 'try_statement', 'catch_clause']
```

**Comment by lukas-reineke** [comment]
I had to change how the highlights are defined to fix #72 , but I didn't know some color schemes reset all highlights on init.
Makes sense I guess. So gruvbox cleared all default highlights for indent-blankline.

I pushed an update now to work around this. It should be fixed now

**Comment by bangn** [comment]
Thanks for your work @lukas-reineke 

Im on the tip of the `lua` branch and looks like it is still not working for me.
Im using `nord` colorscheme FYI.
This commit `d925b80` works for me though

**Comment by lukas-reineke** [comment]
@bangn what is the autoput of `:highlight IndentBlanklineChar`?

**Comment by bangn** [comment]
Hi @lukas-reineke 

Here is mine
```
:highlight IndentBlanklineChar
IndentBlanklineChar xxx gui=nocombine guifg=8
```

Cheers

**Comment by lukas-reineke** [comment]
I see. I only fixed it for gui colors, cterm was still broken.

Pushed an update now, can you check :pray:

**Comment by bangn** [comment]
Work like a charm. Thank you very much @lukas-reineke

**Comment by Gelio** [comment]
Thank you @lukas-reineke for a very quick fix 👍 I can confirm it's working for me too using gruvbox.
