### ISSUE TITLE
Whitespace on blank lines creates indentation guides

### ISSUE THREAD

**Issue by mlhktp** [lukas-reineke/indent-blankline.nvim#978]
### Problem

I would like to ignore whitespace on blank lines so that it does not create indentation guides. I tried using the `remove_blankline_trail` parameter, but it does not seem to work.

As a workaround, I tried the following hook:
```lua
hooks.register(hooks.type.SKIP_LINE, function(_, _, _, line)
    return line:match("^%s*$") ~= nil
end)
```

This successfully removes the extra indentation guides on blank lines, but it also prevents indentation guides from continuing across empty lines.

Before workaround:

![Image](https://github.com/user-attachments/assets/07bcbd05-c40f-4ae3-8d50-ead5a6ce17ce)

After workaround:

![Image](https://github.com/user-attachments/assets/ffc7da4f-0128-4503-a98d-148ea94f3a2a)

### Steps to reproduce

You can reproduce the issue using the following min-init.lua script:

```lua
local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

vim.opt.expandtab = true
vim.opt.tabstop = 3
vim.opt.shiftwidth = 3
vim.opt.softtabstop = 3

require("lazy").setup ({
    {
        "lukas-reineke/indent-blankline.nvim",
        config = function()
          local highlight = {
              "RainbowRed",
              "RainbowYellow",
              "RainbowBlue",
              "RainbowOrange",
              "RainbowGreen",
              "RainbowViolet",
              "RainbowCyan",
          }
          local hooks = require "ibl.hooks"
          hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
              vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
              vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
              vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
              vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
              vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
              vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
              vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
          end)

          require("ibl").setup {
             indent = {
                highlight = highlight,
                char = "▏",
                repeat_linebreak = true,
             },
             whitespace = {
                remove_blankline_trail = true,
             },

          }
          hooks.register(hooks.type.WHITESPACE, hooks.builtin.hide_first_space_indent_level)
          hooks.register(hooks.type.WHITESPACE, hooks.builtin.hide_first_tab_indent_level)

          -- hooks.register(hooks.type.SKIP_LINE, function(_, _, _, line)
          --     return line:match("^%s*$") ~= nil
          -- end)


        end,
    },
}, { root = "/tmp/lazy" })
```

### Expected behavior

Whitespace on blank lines should not generate additional indentation guides, but indentation guides should still continue across blank lines.

### Neovim version (nvim -v)

0.10.4

**Comment by lukas-reineke** [comment]
I'm not sure I understand your problem.

> Whitespace on blank lines should not generate additional indentation guides, but indentation guides should still continue across blank lines.

This is the default behavior.

**Comment by mlhktp** [comment]
As you can see from the image below, currently the marked whitespace creates the yellow indentation guide.

**Current Behaviour:**

![Image](https://github.com/user-attachments/assets/85c5d549-a8a0-4d58-a96e-edc80bd316e2)

However, I would like that whitespace to be ignored.

**Expected Behaviour:**

![Image](https://github.com/user-attachments/assets/61704a72-d81d-488e-ba5f-b9b8a9b960a1)

**Comment by lukas-reineke** [comment]
Thanks, I understand what you mean now.
I agree, a line with only whitespace should not add a new indentation level.

I'll try to fix this at some point, but it might take a while, sorry.

**Comment by lukas-reineke** [comment]
Should be fixed in the latest version

**Comment by vricop** [comment]
This is still not fixed. Only happening when you're getting to the end of the file though
